env:   
  node: true

extends:
  - 'airbnb-base'

rules:
  no-prototype-builtins: 0
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  linebreak-style: 0